{% set name = "Flask" %}
{% set version = "1.0.2" %}
{% set hash_type = "sha256" %}
{% set hash = "2271c0070dbcb5275fad4a82e29f23ab92682dc45f9dfbc22c02ba9b9322ce48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - flask = flask.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - click >=2.0
    - itsdangerous >=0.21
    - jinja2 >=2.4
    - werkzeug >=0.7

test:
  imports:
    - flask
    - flask.ext

  commands:
    - flask --help

about:
  home: http://flask.pocoo.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A microframework based on Werkzeug, Jinja2 and good intentions.
  description: |
    Flask is a microframework for Python based on Werkzeug and Jinja2. It's
    intended for getting started very quickly and was developed with best
    intentions in mind.
  doc_url: http://flask.pocoo.org/docs/0.12
  doc_source_url: https://github.com/pallets/flask/blob/master/docs/index.rst
  dev_url: https://github.com/pallets/flask

extra:
  recipe-maintainers:
    - goanpeca
    - nehaljwani
