travis:
  secure:
    BINSTAR_TOKEN: NDgKgUp8whv7oV/50RRpWlX8vTcTqJzBShqLtwaIDx/dBGlUqVYoiOFZ5Dw6qE3g5ujZeMguRFmzS3LsIoGPc6P+Wm9DsMVh9MK9lxHMYaYK3ipCBk5Oy7nwcie/Csx4b5snvnaKIII10JEelK8plvLtofTOTf2NFSbUtdG8CuAiiUHL+OfHHP2EGdpn5ufppGZO0hex3vqq2wWuhIqWaqw2S85SXqQExm0qxQ6ZzgiF6qM/G/y5cWijQwrRmMTmlKBCXeYEX4Us//kGMCKc2amiheBPlImksZPkxkN0Wj3z4IzfC23BRQ8BCrTX4T95ZRPdsgKz4ArUNy14triLt54C3vXwJ5ToQGnvX+bI3K7sIk7gNKXXaB9ClIRp8LR3CuNuMIOQL7tpqlloH6YzpmxJYG81dhAL+2RF1rlS5pPcwYjFE+omyrl1ghdmpk1WshMWSmvQFP47HSRSJ5D7jaiUKOkv4yAypKd/Qty4UsGnQ+eAKquZmZzJGWDAp+uClyo+0aHsvEfhUs6gRQb3+Cjlq8bJjh0ECgFKL4QmAUCawl0goyhjmKNndzmuDHJTYCSuvy4tcr0Z6Mp3Cez8bC6mFytYy71hYk8caCqstiP2JZf7hgkjHdOXUo2uawMqTDCdoZzm+q1IejBrFZMYa269IH0oz3m6ccRhZ83I8Js=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
